### ISSUE TITLE
Error authenticating with Azure Container Registry

### ISSUE THREAD

**Issue by bdehamer** [github-early-access/generate-build-provenance#114]
When using the `push-to-registry` option in conjunction with Azure Container Registry (ACR), I'm seeing the following error:

```
Error: Error uploading artifact to container registry
##[debug]Error fetching https://pkgsecdemo.azurecr.io/oauth2/token?service=pkgsecdemo.azurecr.io&scope=repository%3Astore-front%3Apull%2Cpush - expected 200, received 401
```

The workflow exhibiting the error is authenticating with ACR via workload identity federation (GHA OIDC token exchanged for a service principal access token).

```yaml
- name: Log in to Azure
  uses: azure/login@v1.6.1
  with:
    client-id: ${{ vars.AZURE_CLIENT_ID }}
    tenant-id: ${{ vars.AZURE_TENANT_ID }}
    subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
- name: Set up docker credentials
  run:
    az acr login --name ${{ env.REGISTRY }}
```

When using this style of auth, the credentials written to the `.docker/config.json` file have the following format:

```json
{
  "auths": {
    "pkgsecdemo.azurecr.io": {
      "auth": "MDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwOg==",
      "identitytoken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpX..."
    }
  }
}
```

This is different than the config used by most other registries which provide only an `auth` value.

In this case, the `auth` field decodes to `00000000-0000-0000-0000-000000000000:` and does NOT contain the expected password.

In cases like this where an `identitytoken` field is present, the credentials should be assembled by taking the username from the `auth` field and using the `identitytoken` as the password.

The [`getRegistryCredentials`](https://github.com/github-early-access/generate-build-provenance/blob/f9f24b5dabd264a00bab305f7edd66244d7dcce0/src/oci/credentials.ts#L16) function should be updated to accommodate this alternate form of storing the registry creds.
